.TH tempread 8 
.SH NAME 
tempread \- reads detects changes in tempature from starting temp
.SH SYNOPSIS 
.B tempread 
[\fB\-v\fR] 
[\fB\-\-d\fR \fIDevice\fR] 
.IR file ... 
.SH DESCRIPTION 
.B tempread 
reads detects changes in tempature from starting temp
.SH OPTIONS 
.TP 
.BR \-v ", " \-d =\fIDevice\fR 
sets if its verbose and the device its looking for
